<script setup lang="ts">
import { onMounted, ref } from 'vue'
import ConfirmActionSheet from '@/components/ConfirmActionSheet.vue'
import { useApp } from '@/composables/useApp'
import { confirmAiAction, sendAiMessage } from '@/services/aiService'
import type { PendingAction } from '@/types'
import { startOfWeek, weekLabel, todayISO } from '@/utils/date'
const {state,refresh}=useApp();const text=ref('');const busy=ref(false);const pending=ref<PendingAction|null>(null);const messages=ref<{from:'user'|'ai';text:string}[]>([{from:'ai',text:'Chào anh 👋 Hãy nói việc cần phân công hoặc hỏi tôi về lịch.'}]);const listening=ref(false)
onMounted(refresh)
async function send(){if(!text.value.trim()||!state.data||!state.profile)return;const q=text.value.trim();messages.value.push({from:'user',text:q});text.value='';busy.value=true;try{const r=await sendAiMessage(q,state.data,state.profile);if(r.kind==='pending'){pending.value=r.action;messages.value.push({from:'ai',text:'Tôi đã hiểu yêu cầu. Vui lòng kiểm tra bản xem trước và xác nhận.'})}else messages.value.push({from:'ai',text:r.text})}catch(e:any){messages.value.push({from:'ai',text:`Có lỗi: ${e?.message??'Không xử lý được yêu cầu'}`})}finally{busy.value=false}}
async function confirm(){if(!pending.value||!state.data)return;busy.value=true;try{const r=await confirmAiAction(pending.value.id,state.data);messages.value.push({from:'ai',text:`✅ ${r.message}`});pending.value=null;await refresh()}catch(e:any){messages.value.push({from:'ai',text:`Không thể lưu: ${e?.message??'Lỗi xác nhận'}`})}finally{busy.value=false}}
function mic(){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){messages.value.push({from:'ai',text:'Trình duyệt này chưa hỗ trợ nhập giọng nói. Anh có thể nhập bằng bàn phím.'});return}const r=new SR();r.lang='vi-VN';r.interimResults=false;r.onstart=()=>listening.value=true;r.onend=()=>listening.value=false;r.onresult=(e:any)=>{text.value=e.results[0][0].transcript};r.start()}
</script>
<template><div class="ai-page" v-if="state.data&&state.profile"><header><div><div class="eyebrow">TRỢ LÝ TNTT</div><h1>✨ AI Phân công</h1><small>Tuần {{weekLabel(startOfWeek(todayISO()))}}</small></div><div class="safety">✓ Luôn hỏi xác nhận</div></header><main class="chat"><div v-for="(m,i) in messages" :key="i" class="bubble" :class="m.from"><span v-if="m.from==='ai'">✨</span><div>{{m.text}}</div></div><div v-if="busy" class="bubble ai">✨ <div>Đang xử lý…</div></div></main><footer><div class="suggestions"><button @click="text='Tuần này ngành nào đọc sách?'">Ai đọc sách?</button><button @click="text='CN này ai bán kem?'">Ai bán kem?</button><button @click="text='T2 Minh Thư đọc sách, T3 Đức đọc sách, T5 Tuyền đọc sách'">Demo phân công</button></div><div class="composer"><button class="mic" :class="{on:listening}" @click="mic">🎤</button><textarea v-model="text" rows="1" placeholder="Nhập: T2 Minh Thư, T3 Đức..." @keydown.enter.exact.prevent="send"></textarea><button class="send" @click="send">➤</button></div></footer><ConfirmActionSheet v-if="pending" :action="pending" @cancel="pending=null" @confirm="confirm"/></div></template>
<style scoped>.ai-page{min-height:calc(100vh - 78px);max-width:760px;margin:auto;display:flex;flex-direction:column;background:#f8fafc}.ai-page header{padding:18px 15px 12px;background:white;border-bottom:1px solid #e8edf4;display:flex;justify-content:space-between;align-items:center}.ai-page h1{font-size:1.35rem;margin:2px 0}.ai-page header small{color:#64748b}.safety{font-size:.72rem;background:#ecfdf5;color:#047857;padding:7px 9px;border-radius:999px;font-weight:800}.chat{flex:1;padding:14px;display:flex;flex-direction:column;gap:10px;overflow:auto}.bubble{max-width:88%;display:flex;gap:7px;white-space:pre-line;line-height:1.42}.bubble>div{padding:11px 13px;border-radius:17px}.bubble.ai{align-self:flex-start}.bubble.ai>div{background:white;border:1px solid #e2e8f0}.bubble.user{align-self:flex-end}.bubble.user>div{background:#1d4ed8;color:white}.ai-page footer{position:sticky;bottom:72px;background:#fff;border-top:1px solid #e2e8f0;padding:9px 10px calc(9px + env(safe-area-inset-bottom))}.suggestions{display:flex;gap:7px;overflow:auto;padding-bottom:8px}.suggestions button{white-space:nowrap;border:1px solid #dbeafe;background:#eff6ff;color:#1e40af;border-radius:999px;padding:7px 9px;font-size:.74rem;font-weight:700}.composer{display:grid;grid-template-columns:42px 1fr 42px;gap:7px;align-items:end}.composer textarea{resize:none;border:1px solid #dbe3ee;border-radius:15px;padding:11px;min-height:44px;max-height:100px}.mic,.send{border:0;width:42px;height:42px;border-radius:50%}.mic{background:#f1f5f9}.mic.on{background:#fee2e2}.send{background:#1d4ed8;color:#fff}</style>
