<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import BranchBadge from '@/components/BranchBadge.vue'
import EmptyState from '@/components/EmptyState.vue'
import ScheduleEditor from '@/components/ScheduleEditor.vue'
import { useApp } from '@/composables/useApp'
import { copyWeek, deleteSchedule, saveSchedule } from '@/services/dataService'
import type { Schedule } from '@/types'
import { addDays, datesOfWeek, formatShortDate, readingBranchForDate, startOfWeek, todayISO, weekdayLabel, weekLabel } from '@/utils/date'
const {state,refresh}=useApp();const cursor=ref(todayISO());const branchFilter=ref('ALL');const showEditor=ref(false);const editing=ref<Schedule|null>(null)
onMounted(refresh)
const days=computed(()=>datesOfWeek(cursor.value))
const readingBranch=computed(()=>state.data?readingBranchForDate(cursor.value,state.data.rotation,state.data.branches):undefined)
const isReadingDay=(d:string)=>[1,2,4,0].includes(new Date(`${d}T12:00:00+07:00`).getDay())
const hasReading=(d:string)=>state.data?.schedules.some(s=>s.date===d&&s.taskCode==='READING')??false
const itemsFor=(d:string)=>state.data?.schedules.filter(s=>s.date===d&&(branchFilter.value==='ALL'||s.branchId===branchFilter.value)).sort((a,b)=>(a.startTime||'99:99').localeCompare(b.startTime||'99:99'))??[]
function branchOf(s:Schedule){return state.data?.branches.find(b=>b.id===s.branchId)}
function canEdit(s:Schedule){return state.profile?.role==='SUPER_ADMIN'||s.branchId===state.profile?.branchId}
async function save(s:any){await saveSchedule(s);showEditor.value=false;editing.value=null;await refresh()}
async function remove(s:Schedule){if(!confirm(`Xóa lịch ${s.taskName}?`))return;await deleteSchedule(s.id);editing.value=null;await refresh()}
async function copyPrevious(){const target=startOfWeek(cursor.value);const source=addDays(target,-7);const bid=state.profile?.role==='BRANCH_ADMIN'?state.profile.branchId:(branchFilter.value==='ALL'?null:branchFilter.value);if(!confirm(`Sao chép các lịch (trừ đọc sách) từ tuần ${weekLabel(source)} sang ${weekLabel(target)}${bid?' cho Ngành đang lọc':''}?`))return;const n=await copyWeek(source,target,bid);alert(`Đã sao chép ${n} lịch. Lịch trùng được bỏ qua.`);await refresh()}
</script>
<template><div class="page" v-if="state.data&&state.profile"><div class="page-head"><div><div class="eyebrow">LỊCH CHUNG</div><h1>{{weekLabel(cursor)}}</h1></div><button class="primary-btn" @click="showEditor=true">＋ Tạo lịch</button></div>
<div class="reading-week" v-if="readingBranch" :style="{'--c':readingBranch.colorHex}"><span>📖 Tuần đọc sách</span><BranchBadge :branch="readingBranch"/></div><button class="copy-btn" @click="copyPrevious">📋 Sao chép tuần trước</button><div class="week-switch"><button @click="cursor=addDays(startOfWeek(cursor),-7)">‹</button><button @click="cursor=todayISO()">Tuần này</button><button @click="cursor=addDays(startOfWeek(cursor),7)">›</button></div>
<div class="filters"><button :class="{active:branchFilter==='ALL'}" @click="branchFilter='ALL'">Tất cả</button><button v-for="b in state.data.branches" :key="b.id" :style="{'--c':b.colorHex}" :class="{active:branchFilter===b.id}" @click="branchFilter=b.id">{{b.name}}</button></div>
<div class="agenda"><section v-for="d in days" :key="d" class="day"><div class="date"><strong>{{weekdayLabel(d)}}</strong><span>{{formatShortDate(d)}}</span></div><div class="day-list"><div v-if="isReadingDay(d)&&!hasReading(d)&&(branchFilter==='ALL'||branchFilter===readingBranch?.id)" class="reading-placeholder" :style="{'--c':readingBranch?.colorHex}"><div><strong>📖 Đọc sách</strong><small>Chưa phân công người/lớp</small></div><BranchBadge :branch="readingBranch"/></div><template v-if="itemsFor(d).length"><button v-for="s in itemsFor(d)" :key="s.id" class="agenda-item" :style="{'--c':branchOf(s)?.colorHex}" @click="canEdit(s)&&(editing=s,showEditor=true)"><div><strong>{{s.taskCode==='READING'?'📖':s.taskCode==='ICE_CREAM'?'🍦':s.taskCode==='OFFICE_DUTY'?'🏢':'🧹'}} {{s.taskName}}</strong><small>{{s.startTime||''}}{{s.endTime?`–${s.endTime}`:''}} · {{s.assignees.map(a=>a.label).join(', ')||'Chưa phân công'}}</small></div><BranchBadge :branch="branchOf(s)"/></button></template><EmptyState v-else-if="!(isReadingDay(d)&&!hasReading(d)&&(branchFilter==='ALL'||branchFilter===readingBranch?.id))" title="Trống" /></div></section></div>
<ScheduleEditor v-if="showEditor" :data="state.data" :profile="state.profile" :existing="editing" @cancel="showEditor=false;editing=null" @save="save"/><div v-if="editing&&showEditor&&canEdit(editing)" class="delete-floating"><button @click="remove(editing)">Xóa lịch này</button></div></div></template>
<style scoped>.copy-btn{width:100%;border:1px solid #dbeafe;background:#eff6ff;color:#1e40af;border-radius:12px;padding:9px;font-weight:800;margin-bottom:8px}.reading-week{display:flex;align-items:center;justify-content:space-between;background:color-mix(in srgb,var(--c) 10%,white);border:1px solid color-mix(in srgb,var(--c) 24%,white);border-radius:15px;padding:10px 12px;margin-bottom:10px;font-weight:800}.reading-placeholder{border:1px dashed var(--c);background:color-mix(in srgb,var(--c) 6%,white);border-radius:14px;padding:11px;display:flex;align-items:center;justify-content:space-between;gap:8px}.reading-placeholder small{display:block;color:#64748b;margin-top:4px}.week-switch{display:grid;grid-template-columns:46px 1fr 46px;gap:8px;margin-bottom:10px}.week-switch button,.filters button{border:1px solid #e2e8f0;background:#fff;border-radius:12px;padding:9px;font-weight:800}.filters{display:flex;gap:7px;overflow:auto;padding-bottom:10px}.filters button{white-space:nowrap}.filters button.active{background:#0f172a;color:#fff}.agenda{display:grid;gap:10px}.day{display:grid;grid-template-columns:50px 1fr;gap:9px}.date{padding-top:9px;text-align:center}.date strong{display:block;font-size:.82rem;color:#475569}.date span{font-size:.72rem;color:#94a3b8}.day-list{display:grid;gap:7px}.agenda-item{width:100%;border:1px solid #e7edf5;border-left:5px solid var(--c);background:#fff;border-radius:14px;padding:11px;text-align:left;display:flex;justify-content:space-between;align-items:center;gap:8px}.agenda-item strong{display:block}.agenda-item small{display:block;color:#64748b;margin-top:4px}.delete-floating{position:fixed;bottom:92px;left:50%;transform:translateX(-50%);z-index:45}.delete-floating button{border:0;background:#fee2e2;color:#991b1b;border-radius:12px;padding:10px 14px;font-weight:800}</style>
