<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuth } from '@/composables/useAuth'
import { bootstrapProfile, getCurrentProfile } from '@/services/dataService'
import { usernameToAuthEmail } from '@/utils/username'
const router=useRouter();const{signIn,busy,error}=useAuth();const username=ref('');const password=ref('');const fullName=ref('Ban Điều Hành');const firstSetup=ref(false)
async function login(){try{await signIn(usernameToAuthEmail(username.value),password.value);let p=await getCurrentProfile();if(!p){firstSetup.value=true;return}router.replace('/')}catch{} }
async function bootstrap(){try{await bootstrapProfile(fullName.value);router.replace('/')}catch(e:any){alert(e.message)}}
</script>
<template><div class="login"><div class="brand"><img class="logo" src="/icon-192.png" alt="Logo Đoàn TNTT Đaminh Saviô" /><h1>Đoàn TNTT Đaminh Saviô</h1><p>Lịch công tác · Nhắc việc · Điểm danh</p></div><section class="card" v-if="!firstSetup"><input v-model="username" type="text" autocapitalize="off" placeholder="Tên đăng nhập"><input v-model="password" type="password" placeholder="Mật khẩu" @keydown.enter="login"><button :disabled="busy" @click="login">{{busy?'Đang đăng nhập…':'Đăng nhập'}}</button><p class="err" v-if="error">{{error}}</p></section><section class="card" v-else><h3>Thiết lập Super Admin đầu tiên</h3><p>Hệ thống chưa có quản trị viên. Tài khoản này sẽ trở thành Super Admin đầu tiên.</p><input v-model="fullName" placeholder="Tên hiển thị"><button @click="bootstrap">Tạo Super Admin</button></section></div></template>
<style scoped>.login{min-height:100%;display:grid;place-content:center;gap:18px;padding:22px 16px}.brand{text-align:center;max-width:390px}.logo{margin:auto;width:92px;height:92px;border-radius:50%;display:block;object-fit:cover;background:#fff;box-shadow:0 0 0 3px #fff,0 0 0 5px #fecaca,0 12px 30px rgba(220,38,38,.18)}h1{margin:14px 0 4px;font-size:clamp(1.3rem,6.2vw,1.6rem);color:#7f1d1d;line-height:1.2}.brand p{margin:0;color:#64748b;font-weight:700;font-size:.86rem}.card{width:min(390px,calc(100vw - 36px));background:white;border:1px solid #e2e8f0;border-radius:20px;padding:16px;display:grid;gap:10px;box-shadow:0 10px 30px rgba(15,23,42,.08)}input{border:1px solid #dbe3ee;border-radius:12px;padding:12px}.card button{border:0;border-radius:12px;padding:12px;background:#1d4ed8;color:#fff;font-weight:800}.card p{font-size:.83rem;color:#64748b}.err{color:#b91c1c!important}</style>