<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import BranchBadge from '@/components/BranchBadge.vue'
import { useApp } from '@/composables/useApp'
import { useAuth } from '@/composables/useAuth'
import { isSupabaseConfigured, supabase } from '@/lib/supabase'
import { resetDemo, setDemoProfile } from '@/services/dataService'
import { usernameToAuthEmail } from '@/utils/username'
const {state,refresh}=useApp();const {signOut,demoMode}=useAuth();const router=useRouter();const username=ref('');const password=ref('');const fullName=ref('');const branchId=ref('');const creating=ref(false);const message=ref('')
onMounted(refresh)
async function logout(){await signOut();if(demoMode){resetDemo();location.reload()}else router.replace('/login')}
async function createAdmin(){if(!supabase||!username.value||!password.value||!fullName.value||!branchId.value)return;creating.value=true;message.value='';const{data,error}=await supabase.functions.invoke('admin-create-user',{body:{email:usernameToAuthEmail(username.value),password:password.value,full_name:fullName.value,branch_id:branchId.value}});creating.value=false;message.value=error?error.message:(data?.message??'Đã tạo tài khoản');}
async function switchDemo(bid:string|null){if(!state.profile)return;setDemoProfile({...state.profile,role:bid?'BRANCH_ADMIN':'SUPER_ADMIN',branchId:bid,fullName:bid?`Admin ${state.data?.branches.find(b=>b.id===bid)?.name}`:'Trưởng Đoàn'});await refresh()}
</script>
<template><div class="page" v-if="state.profile&&state.data"><div class="eyebrow">TÀI KHOẢN</div><h1>Cá nhân 👤</h1><section class="surface profile"><div class="avatar">{{state.profile.fullName.slice(0,1).toUpperCase()}}</div><div><strong>{{state.profile.fullName}}</strong><div class="subtle">{{state.profile.role==='SUPER_ADMIN'?'Super Admin':'Admin Ngành'}}</div><BranchBadge v-if="state.profile.branchId" :branch="state.data.branches.find(b=>b.id===state.profile?.branchId)"/></div></section>
<h2>Quản lý</h2><div class="stack"><button v-if="state.profile.role==='SUPER_ADMIN'" class="menu" @click="router.push('/reading-config')"><span>📖 Cấu hình vòng đọc sách</span><b>›</b></button><button v-if="state.profile.role==='SUPER_ADMIN'" class="menu" @click="router.push('/activity-log')"><span>🧾 Activity Log</span><b>›</b></button></div>
<section v-if="demoMode" class="surface demo"><strong>🧪 Chế độ Demo</strong><p>Chuyển vai để thử quyền “xem chung – sửa riêng”.</p><div class="demo-grid"><button @click="switchDemo(null)">Super Admin</button><button v-for="b in state.data.branches" :key="b.id" @click="switchDemo(b.id)">Admin {{b.name}}</button></div></section>
<section v-if="state.profile.role==='SUPER_ADMIN'&&isSupabaseConfigured" class="surface"><strong>➕ Tạo Admin Ngành</strong><p class="subtle">Tạo tài khoản đăng nhập mới cho một Ngành.</p><input v-model="fullName" placeholder="Họ tên"/><input v-model="username" type="text" autocapitalize="off" placeholder="Tên đăng nhập"/><input v-model="password" type="password" placeholder="Mật khẩu ban đầu"/><select v-model="branchId"><option value="">Chọn Ngành</option><option v-for="b in state.data.branches" :key="b.id" :value="b.id">{{b.name}}</option></select><button class="primary-btn" :disabled="creating" @click="createAdmin">{{creating?'Đang tạo…':'Tạo tài khoản'}}</button><div class="subtle" v-if="message">{{message}}</div></section>
<button class="logout" @click="logout">{{demoMode?'Reset dữ liệu demo':'Đăng xuất'}}</button></div></template>
<style scoped>.profile{display:flex;align-items:center;gap:13px}.avatar{width:54px;height:54px;border-radius:17px;background:#dbeafe;color:#1d4ed8;display:grid;place-items:center;font-size:1.4rem;font-weight:900}.menu{border:1px solid #e2e8f0;background:#fff;border-radius:15px;padding:14px;display:flex;justify-content:space-between;font-weight:800}.demo{margin-top:18px;background:#fffbeb}.demo p{font-size:.83rem;color:#78716c}.demo-grid{display:flex;flex-wrap:wrap;gap:6px}.demo-grid button{border:1px solid #fde68a;background:#fff;border-radius:10px;padding:7px 9px}.surface input,.surface select{width:100%;border:1px solid #dbe3ee;border-radius:11px;padding:10px;margin-top:8px}.surface .primary-btn{width:100%;margin-top:10px}.logout{width:100%;margin-top:22px;border:0;background:#fee2e2;color:#991b1b;border-radius:13px;padding:12px;font-weight:800}</style>
